In [1]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

# 1. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [2]:
## your code
a = (2*np.ones(20))**np.arange(1,21,1)/np.arange(1,21,1)
a

array([2.00000000e+00, 2.00000000e+00, 2.66666667e+00, 4.00000000e+00,
       6.40000000e+00, 1.06666667e+01, 1.82857143e+01, 3.20000000e+01,
       5.68888889e+01, 1.02400000e+02, 1.86181818e+02, 3.41333333e+02,
       6.30153846e+02, 1.17028571e+03, 2.18453333e+03, 4.09600000e+03,
       7.71011765e+03, 1.45635556e+04, 2.75941053e+04, 5.24288000e+04])

**2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [3]:
## your code
sum((np.ones(6)/10)**(3*np.arange(0,6,1))*(np.ones(6)/5)**(4*np.arange(0,6,1)))

1.00000160000256

**3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [4]:
## your code
(np.arange(0,8,1)+np.arange(0,8,1).reshape(8,1)+1)%2

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]], dtype=int32)

**4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [5]:
X = np.random.random((5, 2))

## your code
np.array([np.sqrt(np.sum(X**2,axis=1)),np.arccos(X.T[0]/np.sqrt(np.sum(X**2,axis=1)))]).T

array([[1.22082645, 0.71666114],
       [0.51156642, 1.28175891],
       [0.68988921, 0.10846132],
       [0.74520295, 1.14393745],
       [0.87490904, 1.40694581]])

**5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [6]:
X = np.random.random((10, 10))
np.argmax(X),X
a,b = np.argmax(X)%10,np.argmax(X)//10
b,a, X<X[b,a]
## your code

(4, 9, array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
          True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True,
          True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True,
          True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True,
          True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         False],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True,
          True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True,
          True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True,
          True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True,
          True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True,
          True]]))

**6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [7]:
X = np.random.random((10, 2))
y = np.random.random((1, 2))
X[np.sum((X-y)**2, axis = 1).argmax()]
## your code

array([0.01465496, 0.82820018])

**7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [8]:
## your code
foo = lambda x:[x**2 + 2*x + 6, x + 6, x**2+4*x-4]
np.sum(np.array([np.arange(-3,4,1)<0,(np.arange(-3,4,1)>=0)*(np.arange(-3,4,1)<=2),np.arange(-3,4,1)>2],dtype=int)*\
np.array(foo(np.arange(-3,4,1))),axis=0)

array([ 9,  6,  5,  6,  7,  8, 17])

**8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [9]:
X = np.random.random((10, 10))
X1 = np.mean(X,axis = 1).reshape((10,1))
np.sum(X - X1, axis = 1)

## your code

array([-1.11022302e-16,  1.11022302e-16, -7.77156117e-16,  1.33226763e-15,
        8.88178420e-16,  0.00000000e+00, -1.11022302e-16,  1.11022302e-16,
       -1.11022302e-16,  5.55111512e-16])

**9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [10]:
X = np.random.normal(loc=5, scale=2., size=1000)
x_mid = sum(X)/1000
disp = sum((X - x_mid)**2)/1000
x_mid, disp

(4.948005482248115, 4.098449356085175)

**10.** Создать матрицу:

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [11]:
## your code
(np.arange(5)+np.arange(5).reshape(5,1))%5

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 0],
       [2, 3, 4, 0, 1],
       [3, 4, 0, 1, 2],
       [4, 0, 1, 2, 3]], dtype=int32)